/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sksmanager;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YOGA
 */
public class Manager extends javax.swing.JFrame {
    // Variable Public
    public static String nim = FormLogin.userNIM;
    // Inisialisasi Object
    Connection con;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form Dashboard
     */
    
    //Fungsi Mnaager
    public Manager() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("D:/New Folder/sksmanager/src/sksmanager/image/logo.png");
        setIconImage(icon.getImage());
        con = Sksmanager.getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        try {
            stmt = con.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal membuat Statement: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        tampilData();

    }
    
    // Fungsi Tampil Data
    private void tampilData(){
        nim = FormLogin.userNIM;
        DefaultTableModel isitabel = new DefaultTableModel();
        isitabel.addColumn("NOMOR");
        isitabel.addColumn("KODE");
        isitabel.addColumn("MATAKULIAH");
        isitabel.addColumn("SEMESTER");
        isitabel.addColumn("SKS");
        isitabel.addColumn("NILAI");
        isitabel.addColumn("STATUS");
        try{
            rs = stmt.executeQuery("SELECT nomor, kode_matkul, nama_matkul, semester, sks, nilai, status FROM data_manager WHERE nim = '" + nim + "'");
            while(rs.next()){
                isitabel.addRow(new Object[] {rs.getString("nomor"),
                    rs.getString("kode_matkul"),
                    rs.getString("nama_matkul"),
                    rs.getString("semester"),
                    rs.getString("sks"),
                    rs.getString("nilai"),
                    rs.getString("status")});
            }
            jTable1.setModel(isitabel);
        }catch(SQLException e){
            
        }
    }
    
    private void resetInputFields() {
        Tf_nomor.setText("");
        Tf_nama_matkul.setText("");
        Tf_semester.setText("");
        Tf_sks.setText("");
        Tf_nilai.setText("");
        Tf_status.setText("");
        Tf_kode.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_nav = new javax.swing.JPanel();
        btn_dashboard = new javax.swing.JButton();
        btn_manager1 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        panel_dashboard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Tf_nomor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tf_kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tf_nama_matkul = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tf_semester = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tf_sks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tf_nilai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tf_status = new javax.swing.JTextField();
        Btn_save = new javax.swing.JButton();
        Btn_update = new javax.swing.JButton();
        Btn_delete = new javax.swing.JButton();
        Btn_reset = new javax.swing.JButton();
        Btn_select = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        Btn_Generate = new javax.swing.JButton();
        panel_log1 = new javax.swing.JPanel();
        title_manager = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SKS MANAGER | MANAGER");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(990, 654));
        setResizable(false);
        setSize(new java.awt.Dimension(990, 654));

        panel_nav.setBackground(new java.awt.Color(19, 44, 58));
        panel_nav.setForeground(new java.awt.Color(255, 255, 255));

        btn_dashboard.setBackground(new java.awt.Color(19, 44, 58));
        btn_dashboard.setFont(new java.awt.Font("Calibri", 0, 25)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sksmanager/image/home.png"))); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setAlignmentX(0.1F);
        btn_dashboard.setAlignmentY(0.0F);
        btn_dashboard.setBorder(null);
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setIconTextGap(10);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_manager1.setBackground(new java.awt.Color(39, 82, 107));
        btn_manager1.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        btn_manager1.setForeground(new java.awt.Color(255, 255, 255));
        btn_manager1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sksmanager/image/table.png"))); // NOI18N
        btn_manager1.setText("Manager");
        btn_manager1.setActionCommand("");
        btn_manager1.setAlignmentX(0.1F);
        btn_manager1.setAlignmentY(0.0F);
        btn_manager1.setBorder(null);
        btn_manager1.setBorderPainted(false);
        btn_manager1.setIconTextGap(10);
        btn_manager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manager1ActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(19, 44, 58));
        btn_logout.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sksmanager/image/log-out.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setActionCommand("");
        btn_logout.setAlignmentX(0.1F);
        btn_logout.setAlignmentY(0.0F);
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setIconTextGap(10);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_navLayout = new javax.swing.GroupLayout(panel_nav);
        panel_nav.setLayout(panel_navLayout);
        panel_navLayout.setHorizontalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_manager1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_navLayout.setVerticalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navLayout.createSequentialGroup()
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_manager1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashboard.setPreferredSize(new java.awt.Dimension(771, 589));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("NOMOR");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("KODE MATKUL");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("MATA KULIAH");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("SEMESTER");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("SKS");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("NILAI");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("STATUS");

        Btn_save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_save.setForeground(new java.awt.Color(19, 44, 58));
        Btn_save.setText("Save");
        Btn_save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });

        Btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_update.setForeground(new java.awt.Color(19, 44, 58));
        Btn_update.setText("Update");
        Btn_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_update.setEnabled(false);
        Btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_updateActionPerformed(evt);
            }
        });

        Btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_delete.setForeground(new java.awt.Color(19, 44, 58));
        Btn_delete.setText("Delete");
        Btn_delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_delete.setEnabled(false);
        Btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_deleteActionPerformed(evt);
            }
        });

        Btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_reset.setForeground(new java.awt.Color(19, 44, 58));
        Btn_reset.setText("Reset");
        Btn_reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_resetActionPerformed(evt);
            }
        });

        Btn_select.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_select.setForeground(new java.awt.Color(19, 44, 58));
        Btn_select.setText("Select");
        Btn_select.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_selectActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(19, 44, 58));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilihan-", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilihan-", "1", "2", "3", "4", "5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilihan-", "A", "A+", "A-", "B", "B+", "B-", "C", "C+", "C-", "D", "D+", "D-", "E" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilihan-", "LULUS", "TIDAK LULUS" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        Btn_Generate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Generate.setForeground(new java.awt.Color(19, 44, 58));
        Btn_Generate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 44, 58), 2));
        Btn_Generate.setLabel("Generate");
        Btn_Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GenerateActionPerformed(evt);
            }
        });

        panel_log1.setBackground(new java.awt.Color(19, 44, 58));

        title_manager.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        title_manager.setForeground(new java.awt.Color(255, 255, 255));
        title_manager.setText("MANAGER");

        javax.swing.GroupLayout panel_log1Layout = new javax.swing.GroupLayout(panel_log1);
        panel_log1.setLayout(panel_log1Layout);
        panel_log1Layout.setHorizontalGroup(
            panel_log1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_log1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_manager)
                .addContainerGap(534, Short.MAX_VALUE))
        );
        panel_log1Layout.setVerticalGroup(
            panel_log1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_log1Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(title_manager))
        );

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addComponent(panel_log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_dashboardLayout.createSequentialGroup()
                        .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_dashboardLayout.createSequentialGroup()
                                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(48, 48, 48)
                                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Tf_nilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                                    .addComponent(Tf_sks, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tf_semester)
                                    .addComponent(Tf_status)))
                            .addGroup(panel_dashboardLayout.createSequentialGroup()
                                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel_dashboardLayout.createSequentialGroup()
                                        .addComponent(Tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Btn_Generate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Tf_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_dashboardLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tf_nama_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_dashboardLayout.createSequentialGroup()
                                .addComponent(Btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(Btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Generate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tf_nama_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(panel_dashboardLayout.createSequentialGroup()
                        .addComponent(Tf_status, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_manager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manager1ActionPerformed
        
    }//GEN-LAST:event_btn_manager1ActionPerformed

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        String nomor = Tf_nomor.getText();
        String kode = Tf_kode.getText();
        String nama_matkul = Tf_nama_matkul.getText();
        String sks = Tf_sks.getText();
        String nilai = Tf_nilai.getText();
        String status = Tf_status.getText();
        String semester = Tf_semester.getText();

        if (nomor.isEmpty() || kode.isEmpty() || nama_matkul.isEmpty() || semester.isEmpty()|| sks.isEmpty() || nilai.isEmpty() || status.isEmpty() || nim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi!");
        } else {
            try {
                // Query untuk mengecek apakah data dengan kombinasi nomor, kode, nama_matkul, dan nim sudah ada
                String checkSql = "SELECT COUNT(*) AS count FROM data_manager WHERE nomor = '" + nomor
                + "' AND kode_matkul = '" + kode
                + "' AND nama_matkul = '" + nama_matkul
                + "' AND nim = '" + nim + "'";
                rs = stmt.executeQuery(checkSql);
                rs.next();
                
                
                String checkSql2 = "SELECT COUNT(*) AS count FROM data_manager WHERE nim = '" + nim 
                + "' AND kode_matkul = '" + kode
                + "' AND nama_matkul = '" + nama_matkul
                + "' AND nim = '" + nim + "'";
                rs = stmt.executeQuery(checkSql2);
                rs.next();
                int count = rs.getInt("count");

                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Data dengan kombinasi nomor, kode, nama_matkul!");
                } else {
                    // Jika tidak ada data duplikat, lakukan insert
                    String sql = "INSERT INTO data_manager (nomor, kode_matkul, nama_matkul, semester, sks, nilai, status, nim) VALUES ('"
                    + nomor + "', '"
                    + kode + "', '"
                    + nama_matkul + "', '"
                    + semester + "', '"
                    + sks + "', '"
                    + nilai + "', '"
                    + status + "', '"
                    + nim + "')";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
                    tampilData(); // Refresh tabel setelah menambah data
                    resetInputFields(); // Reset inputan
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal menambahkan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void Btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_updateActionPerformed
        String nomor = Tf_nomor.getText();
        String kode = Tf_kode.getText();
        String nama_matkul = Tf_nama_matkul.getText();
        String semester = Tf_semester.getText();
        String sks = Tf_sks.getText();
        String nilai = Tf_nilai.getText();
        String status = Tf_status.getText();

        if (nomor.isEmpty() || kode.isEmpty() || nama_matkul.isEmpty() || semester.isEmpty()|| sks.isEmpty() || nilai.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong untuk memperbarui data!");
        } else {
            try {
                String sql = "UPDATE data_manager SET kode_matkul = '" + kode
                + "', nomor = '" + nomor
                + "', semester = '" + semester
                + "', sks = '" + sks
                + "', nilai = '" + nilai
                + "', status = '" + status
                + "', nama_matkul = '" + nama_matkul
                + "' WHERE kode_matkul = '" + kode + "'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
                tampilData(); // Refresh tabel setelah update
                resetInputFields(); // Reset inputan
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data: " + e.getMessage());
            }
        }
        Btn_save.setEnabled(true);
        Btn_update.setEnabled(false);
        Btn_delete.setEnabled(false);
    }//GEN-LAST:event_Btn_updateActionPerformed

    private void Btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_deleteActionPerformed
        String kode = Tf_kode.getText();

        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "KODE tidak boleh kosong untuk menghapus data!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String sql = "DELETE FROM data_manager WHERE kode_matkul = '" + kode + "'";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    tampilData(); // Refresh tabel setelah delete
                    resetInputFields(); // Reset inputan
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
                }
            }
        }
        Btn_save.setEnabled(true);
        Btn_delete.setEnabled(false);
        Btn_update.setEnabled(false);
    }//GEN-LAST:event_Btn_deleteActionPerformed

    private void Btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_resetActionPerformed
        resetInputFields();
    }//GEN-LAST:event_Btn_resetActionPerformed

    private void Btn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_selectActionPerformed
        int selectedRow = jTable1.getSelectedRow(); // Ambil baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Silakan pilih data di tabel terlebih dahulu!");
        } else {
            // Ambil data dari tabel berdasarkan indeks kolom
            String nomor = jTable1.getValueAt(selectedRow, 0).toString();
            String kode = jTable1.getValueAt(selectedRow, 1).toString();
            String nama_matkul = jTable1.getValueAt(selectedRow, 2).toString();
            String semester = jTable1.getValueAt(selectedRow, 3).toString();
            String sks = jTable1.getValueAt(selectedRow, 4).toString();
            String nilai = jTable1.getValueAt(selectedRow, 5).toString();
            String status = jTable1.getValueAt(selectedRow, 6).toString();

            // Set data ke text field
            Tf_nomor.setText(nomor);
            Tf_nama_matkul.setText(nama_matkul);
            Tf_semester.setText(semester);
            Tf_sks.setText(sks);
            Tf_nilai.setText(nilai);
            Tf_status.setText(status);
            Tf_kode.setText(kode);
            
        }
        Btn_delete.setEnabled(true);
        Btn_update.setEnabled(true);
        Btn_save.setEnabled(false);
    }//GEN-LAST:event_Btn_selectActionPerformed

    private void Btn_GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GenerateActionPerformed
        // Membuat kode random
        String kodeRandom = generateRandomCode(8); // Panjang kode random: 8 karakter
        // Menampilkan kode random di field Tf_kode_matkul
        Tf_kode.setText(kodeRandom);
    }//GEN-LAST:event_Btn_GenerateActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("S1")){
            Tf_semester.setText("Semester 1");
        }else if(jComboBox1.getSelectedItem().equals("S2")){
            Tf_semester.setText("Semester 2");
        }else if(jComboBox1.getSelectedItem().equals("S3")){
            Tf_semester.setText("Semester 3");
        }else if(jComboBox1.getSelectedItem().equals("S4")){
            Tf_semester.setText("Semester 4");
        }else if(jComboBox1.getSelectedItem().equals("S5")){
            Tf_semester.setText("Semester 5");
        }else if(jComboBox1.getSelectedItem().equals("S6")){
            Tf_semester.setText("Semester 6");
        }else if(jComboBox1.getSelectedItem().equals("S7")){
            Tf_semester.setText("Semester 7");
        }else if(jComboBox1.getSelectedItem().equals("S8")){
            Tf_semester.setText("Semester 8");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem().equals("1")){
            Tf_sks.setText("1");
        }else if(jComboBox2.getSelectedItem().equals("2")){
            Tf_sks.setText("2");
        }else if(jComboBox2.getSelectedItem().equals("3")){
            Tf_sks.setText("3");
        }else if(jComboBox2.getSelectedItem().equals("4")){
            Tf_sks.setText("4");
        }else if(jComboBox2.getSelectedItem().equals("5")){
            Tf_sks.setText("5");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(jComboBox3.getSelectedItem().equals("A")){
            Tf_nilai.setText("A");
        }else if(jComboBox3.getSelectedItem().equals("A+")){
            Tf_nilai.setText("A+");
        }else if(jComboBox3.getSelectedItem().equals("A-")){
            Tf_nilai.setText("A-");
        }else if(jComboBox3.getSelectedItem().equals("B")){
            Tf_nilai.setText("B");
        }else if(jComboBox3.getSelectedItem().equals("B+")){
            Tf_nilai.setText("B+");
        }else if(jComboBox3.getSelectedItem().equals("B-")){
            Tf_nilai.setText("B-");
        }else if(jComboBox3.getSelectedItem().equals("C")){
            Tf_nilai.setText("C");
        }else if(jComboBox3.getSelectedItem().equals("C+")){
            Tf_nilai.setText("C+");
        }else if(jComboBox3.getSelectedItem().equals("C-")){
            Tf_nilai.setText("C-");
        }else if(jComboBox3.getSelectedItem().equals("D")){
            Tf_nilai.setText("D");
        }else if(jComboBox3.getSelectedItem().equals("D+")){
            Tf_nilai.setText("D+");
        }else if(jComboBox3.getSelectedItem().equals("D-")){
            Tf_nilai.setText("D-");
        }else if(jComboBox3.getSelectedItem().equals("E")){
            Tf_nilai.setText("E");
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(jComboBox4.getSelectedItem().equals("LULUS")){
            Tf_status.setText("LULUS");
        }else if(jComboBox4.getSelectedItem().equals("TIDAK LULUS")){
            Tf_status.setText("TIDAK LULUS");
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    // Fungsi untuk menghasilkan kode random
    private String generateRandomCode(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder code = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(characters.length());
            code.append(characters.charAt(index));
        }
        return code.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Generate;
    private javax.swing.JButton Btn_delete;
    private javax.swing.JButton Btn_reset;
    private javax.swing.JButton Btn_save;
    private javax.swing.JButton Btn_select;
    private javax.swing.JButton Btn_update;
    private javax.swing.JTextField Tf_kode;
    private javax.swing.JTextField Tf_nama_matkul;
    private javax.swing.JTextField Tf_nilai;
    private javax.swing.JTextField Tf_nomor;
    private javax.swing.JTextField Tf_semester;
    private javax.swing.JTextField Tf_sks;
    private javax.swing.JTextField Tf_status;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manager1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_log1;
    private javax.swing.JPanel panel_nav;
    private javax.swing.JLabel title_manager;
    // End of variables declaration//GEN-END:variables
}
