/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sksmanager;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YOGA
 */
public class Manager extends javax.swing.JFrame {
    
    public static String nim = FormLogin.userNIM;
    Connection con;
    Statement stmt;
    ResultSet rs;
    /**
     * Creates new form Dashboard
     */
    
    
    public Manager() {
        initComponents();
        con = Sksmanager.getConnection();
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        try {
            stmt = con.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal membuat Statement: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        tampilData();

    }

    private void tampilData(){
        nim = FormLogin.userNIM;
        DefaultTableModel isitabel = new DefaultTableModel();
        isitabel.addColumn("ID");
        isitabel.addColumn("KODE");
        isitabel.addColumn("MATAKULIAH");
        isitabel.addColumn("SEMESTER");
        isitabel.addColumn("SKS");
        isitabel.addColumn("NILAI");
        isitabel.addColumn("STATUS");
        try{
            rs = stmt.executeQuery("SELECT id, kode_matkul, nama_matkul, semester, sks, nilai, status FROM data_manager WHERE nim = '" + nim + "'");
            while(rs.next()){
                isitabel.addRow(new Object[] {rs.getString("id"),
                    rs.getString("kode_matkul"),
                    rs.getString("nama_matkul"),
                    rs.getString("semester"),
                    rs.getString("sks"),
                    rs.getString("nilai"),
                    rs.getString("status")});
            }
            jTable1.setModel(isitabel);
        }catch(SQLException e){
            
        }
    }
    
    private void resetInputFields() {
        Tf_id.setText("");
        Tf_nama_matkul.setText("");
        Tf_semester.setText("");
        Tf_sks.setText("");
        Tf_nilai.setText("");
        Tf_status.setText("");
        Tf_kode.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_nav = new javax.swing.JPanel();
        btn_dashboard = new javax.swing.JButton();
        btn_manager1 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        panel_dashboard = new javax.swing.JPanel();
        title_manager = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tf_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tf_kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tf_nama_matkul = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Tf_semester = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tf_sks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tf_nilai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tf_status = new javax.swing.JTextField();
        Btn_save = new javax.swing.JButton();
        Btn_update = new javax.swing.JButton();
        Btn_delete = new javax.swing.JButton();
        Btn_reset = new javax.swing.JButton();
        Btn_select = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SKS MANAGER | DASHBOARD");
        setResizable(false);

        panel_nav.setBackground(new java.awt.Color(19, 44, 58));
        panel_nav.setForeground(new java.awt.Color(255, 255, 255));

        btn_dashboard.setBackground(new java.awt.Color(19, 44, 58));
        btn_dashboard.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setAlignmentX(0.1F);
        btn_dashboard.setAlignmentY(0.0F);
        btn_dashboard.setBorder(null);
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_manager1.setBackground(new java.awt.Color(39, 82, 107));
        btn_manager1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_manager1.setForeground(new java.awt.Color(255, 255, 255));
        btn_manager1.setText("Manager");
        btn_manager1.setActionCommand("");
        btn_manager1.setAlignmentX(0.1F);
        btn_manager1.setAlignmentY(0.0F);
        btn_manager1.setBorder(null);
        btn_manager1.setBorderPainted(false);
        btn_manager1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_manager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manager1ActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(19, 44, 58));
        btn_logout.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.setActionCommand("");
        btn_logout.setAlignmentX(0.1F);
        btn_logout.setAlignmentY(0.0F);
        btn_logout.setBorder(null);
        btn_logout.setBorderPainted(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_navLayout = new javax.swing.GroupLayout(panel_nav);
        panel_nav.setLayout(panel_navLayout);
        panel_navLayout.setHorizontalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_manager1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
            .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_navLayout.setVerticalGroup(
            panel_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navLayout.createSequentialGroup()
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_manager1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_dashboard.setBackground(new java.awt.Color(255, 255, 255));

        title_manager.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        title_manager.setText("MANAGER");

        jLabel2.setText("ID");

        jLabel8.setText("KODE MATKUL");

        jLabel3.setText("MATA KULIAH");

        jLabel9.setText("SEMESTER");

        jLabel4.setText("SKS");

        jLabel5.setText("NILAI");

        jLabel6.setText("STATUS");

        Btn_save.setText("Save");
        Btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_saveActionPerformed(evt);
            }
        });

        Btn_update.setText("Update");
        Btn_update.setEnabled(false);
        Btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_updateActionPerformed(evt);
            }
        });

        Btn_delete.setText("Delete");
        Btn_delete.setEnabled(false);
        Btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_deleteActionPerformed(evt);
            }
        });

        Btn_reset.setText("Reset");
        Btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_resetActionPerformed(evt);
            }
        });

        Btn_select.setText("Select");
        Btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_selectActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(title_manager)
                .addContainerGap(648, Short.MAX_VALUE))
            .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_dashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashboardLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_dashboardLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel_dashboardLayout.createSequentialGroup()
                                            .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(panel_dashboardLayout.createSequentialGroup()
                                                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Btn_update)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Btn_delete)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Btn_reset)))
                                            .addGap(18, 18, 18)
                                            .addComponent(Btn_select)))
                                    .addGap(181, 181, 181))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dashboardLayout.createSequentialGroup()
                                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(58, 58, 58)
                                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dashboardLayout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Tf_nama_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Tf_sks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tf_nilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tf_semester, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tf_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(187, 187, 187)))
                    .addContainerGap()))
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(title_manager)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_dashboardLayout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(Tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Tf_nama_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(Tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(Tf_sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(Tf_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Tf_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_save)
                        .addComponent(Btn_update)
                        .addComponent(Btn_delete)
                        .addComponent(Btn_reset)
                        .addComponent(Btn_select))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(109, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_manager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manager1ActionPerformed
        
    }//GEN-LAST:event_btn_manager1ActionPerformed

    private void Btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_saveActionPerformed
        String id = Tf_id.getText();
        String kode = Tf_kode.getText();
        String nama_matkul = Tf_nama_matkul.getText();
        String sks = Tf_sks.getText();
        String nilai = Tf_nilai.getText();
        String status = Tf_status.getText();
        String semester = Tf_semester.getText();

        if (id.isEmpty() || kode.isEmpty() || nama_matkul.isEmpty() || semester.isEmpty()|| sks.isEmpty() || nilai.isEmpty() || status.isEmpty() || nim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua kolom harus diisi!");
        } else {
            try {
                // Query untuk mengecek apakah data dengan kombinasi id, kode, nama_matkul, dan nim sudah ada
                String checkSql = "SELECT COUNT(*) AS count FROM data_manager WHERE id = '" + id
                + "' AND kode_matkul = '" + kode
                + "' AND nama_matkul = '" + nama_matkul
                + "' AND nim = '" + nim + "'";
                rs = stmt.executeQuery(checkSql);
                rs.next();
                int count = rs.getInt("count");

                if (count > 0) {
                    JOptionPane.showMessageDialog(null, "Data dengan kombinasi id, kode, nama_matkul, dan nim sudah ada!");
                } else {
                    // Jika tidak ada data duplikat, lakukan insert
                    String sql = "INSERT INTO data_manager (id, kode_matkul, nama_matkul, semester, sks, nilai, status, nim) VALUES ('"
                    + id + "', '"
                    + kode + "', '"
                    + nama_matkul + "', '"
                    + semester + "', '"
                    + sks + "', '"
                    + nilai + "', '"
                    + status + "', '"
                    + nim + "')";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
                    tampilData(); // Refresh tabel setelah menambah data
                    resetInputFields(); // Reset inputan
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal menambahkan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_Btn_saveActionPerformed

    private void Btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_updateActionPerformed
        String id = Tf_id.getText();
        String kode = Tf_kode.getText();
        String nama_matkul = Tf_nama_matkul.getText();
        String semester = Tf_semester.getText();
        String sks = Tf_sks.getText();
        String nilai = Tf_nilai.getText();
        String status = Tf_status.getText();

        if (id.isEmpty() || kode.isEmpty() || nama_matkul.isEmpty() || semester.isEmpty()|| sks.isEmpty() || nilai.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong untuk memperbarui data!");
        } else {
            try {
                String sql = "UPDATE data_manager SET nim = '" + nim
                + "', id = '" + id
                + "', semster = '" + semester
                + "', sks = '" + sks
                + "', nilai = '" + nilai
                + "', status = '" + status
                + "', nama_matkul = '" + nama_matkul
                + "' WHERE kode_matkul = '" + kode + "'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
                tampilData(); // Refresh tabel setelah update
                resetInputFields(); // Reset inputan
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data: " + e.getMessage());
            }
        }
        Btn_save.setEnabled(true);
        Btn_update.setEnabled(false);
        Btn_delete.setEnabled(false);
    }//GEN-LAST:event_Btn_updateActionPerformed

    private void Btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_deleteActionPerformed
        String kode = Tf_kode.getText();

        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(null, "KODE tidak boleh kosong untuk menghapus data!");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    String sql = "DELETE FROM data_manager WHERE kode_matkul = '" + kode + "'";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    tampilData(); // Refresh tabel setelah delete
                    resetInputFields(); // Reset inputan
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
                }
            }
        }
        Btn_save.setEnabled(true);
        Btn_delete.setEnabled(false);
        Btn_update.setEnabled(false);
    }//GEN-LAST:event_Btn_deleteActionPerformed

    private void Btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_resetActionPerformed
        resetInputFields();
    }//GEN-LAST:event_Btn_resetActionPerformed

    private void Btn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_selectActionPerformed
        int selectedRow = jTable1.getSelectedRow(); // Ambil baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Silakan pilih data di tabel terlebih dahulu!");
        } else {
            // Ambil data dari tabel berdasarkan indeks kolom
            String id = jTable1.getValueAt(selectedRow, 0).toString();
            String kode = jTable1.getValueAt(selectedRow, 1).toString();
            String nama_matkul = jTable1.getValueAt(selectedRow, 2).toString();
            String semester = jTable1.getValueAt(selectedRow, 3).toString();
            String sks = jTable1.getValueAt(selectedRow, 4).toString();
            String nilai = jTable1.getValueAt(selectedRow, 5).toString();
            String status = jTable1.getValueAt(selectedRow, 6).toString();

            // Set data ke text field
            Tf_id.setText(id);
            Tf_nama_matkul.setText(nama_matkul);
            Tf_semester.setText(semester);
            Tf_sks.setText(sks);
            Tf_nilai.setText(nilai);
            Tf_status.setText(status);
            Tf_kode.setText(kode);
            
        }
        Btn_delete.setEnabled(true);
        Btn_update.setEnabled(true);
        Btn_save.setEnabled(false);
    }//GEN-LAST:event_Btn_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_delete;
    private javax.swing.JButton Btn_reset;
    private javax.swing.JButton Btn_save;
    private javax.swing.JButton Btn_select;
    private javax.swing.JButton Btn_update;
    private javax.swing.JTextField Tf_id;
    private javax.swing.JTextField Tf_kode;
    private javax.swing.JTextField Tf_nama_matkul;
    private javax.swing.JTextField Tf_nilai;
    private javax.swing.JTextField Tf_semester;
    private javax.swing.JTextField Tf_sks;
    private javax.swing.JTextField Tf_status;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manager1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_nav;
    private javax.swing.JLabel title_manager;
    // End of variables declaration//GEN-END:variables
}
